### ISSUE TITLE
demo project 404 error

### ISSUE THREAD

**Issue by pocupine** [TTWShell/hobbit-core#106]
demo project 404 error. Windows,Linux 都有这个问题请问下是怎么回事？

**Comment by TTWShell** [comment]
还请贴一下log，我看一下。

**Comment by pocupine** [comment]
不好意思还很菜。我把本机windows 10 里面把flask_debug turn on, flask_env=development 之后，
还在主程序里面创建了
def register_logging(app):
    app.logger.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    file_handler = RotatingFileHandler(os.path.join(basedir, 'logs/catchatlog.log'),
                                       maxBytes=10 * 1024 * 1024, backupCount=10)
    file_handler.setFormatter(formatter)
    file_handler.setLevel(logging.INFO)

    # if not app.debug:
    app.logger.addHandler(file_handler)

并没有得到有用的信息。
pycharm:
127.0.0.1 - - [27/Aug/2020 08:52:15] "?[33mGET / HTTP/1.1?[0m" 404 -

Chrome
{
"code":"404",
"detail":null,
"message":"\u4e0d\u6b63\u786e\u7684\u94fe\u63a5\u5730\u5740"
}

Firefox
code | "404"
-- | --
detail | null
message | "不正确的链接地址"

对于flask logging 还不是很懂。

**Comment by TTWShell** [comment]
这个和日志没有关系的，  / url没有handler，需要你自己实现，你可以看下生成的代码 app/views/ping.py。建议边学边熟悉。

**Comment by pocupine** [comment]
好的谢谢。才发现templates,static,route 这些全都是自己建的。
