### ISSUE TITLE
新手入坑，项目文档里有些疑问

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [TTWShell/hobbit-core#108]
## 1、
快速生成项目

使用 hobbit 命令自动生成你的flask项目:

hobbit --echo new -n demo -d . -p 5000 --celery  # 建议试用 -t rivendell 新模版

这个   -t rivendell   又是啥？怎么理解和前面`hobbit --echo new -n`的关系？

## 2、
hobbit new
和
hobbite gen 

的区别是啥？

## 3、

hobbit gen 命令可根据一个描叙models的csv文件，自动生成models.py、CRUD 的 API、unittest（目前仅支持rivendell模版）。hobbit create 命令可以生成一个csv文件，含有一些基本的例子。

hobbit --echo gen -n user -d /tmp/test -t rivendell --csv-path xx

结尾的`xx` 又代表啥？

**Comment by sanbeichahegongheguo** [comment]
第一个问题想明白了。

但是输入 `new` 之后报错：
`error:Tpl `shire` not exists.`

这又是啥？搜都搜不出来。

**Comment by TTWShell** [comment]
![image](https://user-images.githubusercontent.com/8017604/106219554-9397d000-6214-11eb-969a-cf386ea0c63d.png)

**Comment by arsMarvin** [comment]
@sanbeichahegongheguo 
关于模板缺失的报错:   error:Tpl shire not exists.
阅读了源码，发现是下面这个方法出现异常。

**Comment by TTWShell** [comment]
@arsMarvin 
![image](https://user-images.githubusercontent.com/8017604/111312020-d6651880-8699-11eb-947f-fd61bb3b2805.png)
安装包是有的，你的python版本，安装命令，安装日志贴一下？

**Comment by sanbeichahegongheguo** [comment]
感谢。我目前这个项目没有继续用咱们这个。不过下一个我会再尝试用一下，再来跟你反馈。
