### ISSUE TITLE
对services 的一些疑问

### ISSUE THREAD

**Issue by zzzdtz** [TTWShell/hobbit-core#122]
使用项目文档自动生成的项目,service里 option.py 是示例文件, 这个目录是需要自己写增删改查？

**Comment by zzzdtz** [comment]
是否增加一些service schemas的例子

**Comment by TTWShell** [comment]
> 使用项目文档自动生成的项目,service里 option.py 是示例文件, 这个目录是需要自己写增删改查？

option.py里面是定义的枚举类型自动返回给前端，方便前后端统一的枚举类型定义。
前端可以自动化检查，保证一致。
业务逻辑可以写在其他文件。

**Comment by TTWShell** [comment]
> 是否增加一些service schemas的例子

这个其实看个人，我们内部倒是有统一的标准。需要哪样的例子？可以具体一些吗？

**Comment by zzzdtz** [comment]
我已经搞明白了，封装了一个UserService 用于 view层调用用户新建、查询、数据修改，我像其他人可能也需要，但是schemas 能有一个API 生成的例子会好一些。这个框架很不错，丰富一点就是python就有类JAVA的若依框架用了

**Comment by TTWShell** [comment]
@zzzdtz 方便的话可以补充下你想要的文档吗？来个examples。

**Comment by zzzdtz** [comment]
@TTWShell  https://github.com/zzzdtz/hobbit-core-dem 我写了一个基于框架的demo例子，可能是之前没接触过schemas, 而框架本身的schemas例子太少，我简单的以为只是生成model的数据序列化好像不太对。所以希望能有一个完成的例子, 是用来解决 views接受参数的验证 和 model 输出字段的控制

**Comment by zzzdtz** [comment]
from hobbit_core.schemas import ORMSchema, SchemaMixin 这2个参数的用法，有查询后返回json的例子, https://github.com/zzzdtz/hobbit-core-demo

**Comment by TTWShell** [comment]
@zzzdtz 可以看下文档 https://hobbit-core.readthedocs.io/zh/latest/api.html#module-hobbit_core.schemas

**Comment by TTWShell** [comment]
@zzzdtz schema的文档，参考：https://github.com/marshmallow-code/marshmallow
